; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_RayShadeOpening1
	dba Music_RayShadeOpening2
	dba Music_MainMenu
	dba Music_HealPokemon
	dba Music_HealAlternate
	dba Music_Route49
	dba Music_Route52
	dba Music_Route55
	dba Music_EquintoLeague
	dba Music_Route61
	dba Music_TimeCapsuleMenu
	dba Music_Mom
	dba Music_HurryAlong
	dba Music_HouseEnroute
	dba Music_PokemonCenter
	dba Music_DilapPokeCenter
	dba Music_CottageTown
	dba Music_TraversalCity
	dba Music_WildBattle
	dba Music_TrainerBattle
	dba Music_GymBattle
	dba Music_PartyHostBattle
	dba Music_ShaggyBattle
	dba Music_ParkerBattle
	dba Music_LookWarden
	dba Music_LookGirl
	dba Music_LookLunatic
	dba Music_LookYouth
	dba Music_LookWoman
	dba Music_LookSibs
	dba Music_LookPartyHost
	dba Music_LookArtist
	dba Music_LookHavoc
	dba Music_LookRival
	dba Music_AfterTheRivalFight
	dba Music_Larch
	dba Music_CatchVictory
	dba Music_WildVictory
	dba Music_TrainerVictory
	dba Music_GymVictory
	dba Music_Gym
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_HallOfFame
	dba Music_OddishFarm
	dba Music_GolemPalace
	dba Music_SunkernSwamp
	dba Music_Event
	dba Music_CreditsExt
	dba Music_TheEnd
	dba Music_LanaweForest
	dba Music_SSVapor
	dba Music_Lighthouse
	dba Music_EastCoastStop
	dba Music_HypercoinCity
	dba Music_MtVacuum
	dba Music_TeamHavocTheme
	dba Music_NorgeoTown
	dba Music_PortiteCity
	dba Music_Printer
	dba Music_Departure
	dba Music_Surf
	dba Music_StampTown
	dba Music_HavocHideout
	dba Music_TradeMenuPart1
	dba Music_TradeMenuPart2
	dba Music_WatchinOverMeJingle
	dba Music_PokeFluteMedley
	dba Music_BestFriendsLullaby
	dba Music_MorningInEquintoMarch
; chaos tracks
	dba Music_LookZach
	dba Music_MarloonEncounter
	dba Music_EquineTrioBattle
	dba Music_ChaosIntro
	dba Music_PilotTegere
	dba Music_MobileLinkBallad
	dba Music_AtTheBattleTower
	dba Music_FindAProfileOption
	dba Music_BattleTowerLobby
	dba Music_PokecomCenter
